---
dependencies: []

galaxy_info:
  author: Gianluca Del Brusco && Giovanni Alo
  description: Kibana for Linux.
  company: "Almaviva"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  galaxy_tags:
    - web
    - system
    - monitoring
