---
- debug:
        msg: "{{logstash_elasticsearch_hosts + 'prova'}}"
  when: elasticsearch_master_is_datanode

- name: set degli host di logstash
  set_fact:
            logstash_elasticsearch_hosts: '{{logstash_elasticsearch_hosts + 'prova'}}'
  when: elasticsearch_master_is_datanode

- debug:
        msg: "{{logstash_elasticsearch_hosts}}"

- name: Include OS Specific setup tasks
  import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: config.yml
- import_tasks: ssl.yml
- import_tasks: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
