---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

#- name: Install Logstash.
#  yum: pkg=logstash state=installed

- name: RedHat - Install Logstash
  become: yes
  yum: name=logstash{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %} state=present update_cache=yes
  when: es_use_repository
  register: redhat_logstash_install_from_repo
  notify: restart logstash
  until: '"failed" not in redhat_logstash_install_from_repo'
  retries: 5
  delay: 10
