---
- name: Create mount Point Folder
  file:
    path: "{{mountpath}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  register: folder_created

- set_fact:
    setup_datadirectory: "{{mountpath}}"
