---
# Create a logical volume the size of all remaining space in the volume group
- lvol:
    vg: "{{vgname}}"
    lv: "{{lvname}}"
    size: "{{lvsize}}"
  when: vg_created|succeeded
  register: lv_created
