---
- name: Mount filesystem
  mount:
    path: "{{mountpath}}"
    src: "/dev/{{vgname}}/{{lvname}}"
    fstype: "{{formatfs}}"
    state: mounted
  when: fs_created|succeeded and folder_created|succeeded
  register: fs_mounted
