- hosts: elk_host_to_discovery
  become: true
  remote_user: centos
  roles:
    - config_file_hosts

- hosts: elastic_server_master
  become: true
  remote_user: centos
  roles:
    - createfs
    - {role: ansible-elasticsearch, es_instance_name: "{{ansible_nodename}}_Master", es_heap_size: "1g", es_data_dirs: "{{setup_datadirectory}}",
    es_config: {
      cluster.name: "{{elastic_Cluster}}",
      discovery.zen.ping.unicast.hosts: "{{master_node}}:9300",
      http.port: 9200,
      network.host: "{{master_node}}",
      transport.tcp.port: 9300,
      node.data: "{{elasticsearch_master_is_datanode}}",
      node.master: true,
      bootstrap.memory_lock: false,
      }
      }
#    - ansible-kibana
    - ansible-logstash
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{ ansible_nodename }}"
    ansible_user: centos
    es_version: "{{ekl_version_to_install}}"
    es_proxy_host: 10.221.0.22
    es_proxy_port: 8080
    es_plugins:
      - plugin: ingest-geoip



- hosts: elastic_server_data
  become: true
  remote_user: centos
  roles:
    - createfs
    - {role: ansible-elasticsearch, es_instance_name: "{{ansible_nodename}}_Data", es_data_dirs: "{{setup_datadirectory}}",
    es_config: {
      cluster.name: "{{elastic_Cluster}}",
      discovery.zen.ping.unicast.hosts: "{{master_node}}:9300",
      http.port: 9200,
      network.host: "{{ansible_nodename}}",
      transport.tcp.port: 9300,
      node.data: true,
      node.master: false,
      bootstrap.memory_lock: false,
      }
      }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{ ansible_nodename }}"
    ansible_user: centos
    es_api_port: 9200
    es_version: "{{ekl_version_to_install}}"
    es_proxy_host: 10.221.0.22
    es_proxy_port: 8080
    es_plugins:
      - plugin: ingest-geoip

# - hosts: logstash_install_host
#   become: true
#   remote_user: centos
#   roles:
#     - ansible-logstash
