elk_version_to_install: 5.6.6
elk_major_version: 5.x
elastic_Cluster: cluster-test
elasticsearch_master_is_datanode: true
master_node: ansible1
data_node1: ansible2
data_node2: ansible3
remote_user: root
