---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Create Folder for kibana configuration
  file:
    path: "{{kibana_conf_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  register: folder_created

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "{{kibana_conf_dir}}/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
